var express=require('express');
var bodyparser=require('body-parser');
var mongoose=require('mongoose');
var db=mongoose.connect('mongodb://localhost/comments');
require('./models/comment_model.js');
require('./models/page_model.js');
require('./photo_model.js');
var app=express();
app.engine('.html',require('ejs').__express);
app.set('views',__dirname+'/views');
app.set('view engine','html');
app.use(bodyparser());
require('./comment_routes')(app);
app.listen(80);